create table person (id int, item int);
insert into person values (1, 1);
insert into person values (2, 2);
insert into person values (3, 3);
insert into person values (4, 4);
insert into person values (5, 5);
insert into person values (6, 6);
insert into person values (7, 7);
insert into person values (8, 8);
insert into person values (9, 9);
insert into person values (10, 10);
insert into person values (11, 11);
insert into person values (12, 12);
insert into person values (13, 13);
insert into person values (14, 14);
insert into person values (15, 15);